<a href="https://colab.research.google.com/github/sadat1971/PyTorch_practice/blob/main/001_torch_basic_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Operations on PyTorch

This Notebook contains the basic operations on pytorch as inspired by https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [2]:
import torch
import numpy as np
from __future__ import print_function

## torch.empty
An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

In [3]:
torch.empty(size=(2,3))

tensor([[3.6461e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

## torch.rand
The randomly initialized tensor in pytorch. The output is an uniform distribution between 0 and 1

In [4]:
X= torch.rand(size=(2,3))
print("A random torch tensor", X)
print("The shape of X is ", X.shape)

A random torch tensor tensor([[0.7235, 0.4596, 0.1239],
        [0.0179, 0.4553, 0.4465]])
The shape of X is  torch.Size([2, 3])


## torch.tensor
Creating a tensor

In [5]:
T_1_D = torch.tensor([2,4,6,7]) #1-D tensor
T_2_D = torch.tensor([[1, 2, 3],[9, 4, 5]]) #2-D tensor 
print("The shape of T_1_D is", T_1_D.shape)
print("The shape of T_2_D is", T_2_D.shape)

The shape of T_1_D is torch.Size([4])
The shape of T_2_D is torch.Size([2, 3])


# Tensor Based on Existing Tensor

Tensors can be built based on an existing tensor. In that process we can copy the dtype and decvice use (CPU or GPU) of an existing tensor

In [6]:
A = torch.tensor([[2, 3.99, 8], [34, 0.008, -1]])
print("Data Type of A is", A.dtype)
B = A.new_tensor([2,11,.0009])
print("Data Type of B is", B.dtype)
print(B)
C = A.new_ones(4, 9)
print(C)
print("Data Type of C is", C.dtype)
# we can also override 
D = A.new_full(size=(2,4), fill_value=7, dtype=torch.int32)
print("The tensor D is", D)
print("Data Type of D is", D.dtype)

Data Type of A is torch.float32
Data Type of B is torch.float32
tensor([2.0000e+00, 1.1000e+01, 9.0000e-04])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
Data Type of C is torch.float32
The tensor D is tensor([[7, 7, 7, 7],
        [7, 7, 7, 7]], dtype=torch.int32)
Data Type of D is torch.int32


In [7]:
# We can also make a random tensor based on the existing one
torch.randn_like(D, dtype=torch.float32) 

tensor([[-0.5032,  0.2559, -1.0338, -1.1947],
        [-0.6212, -1.2323,  0.4886, -0.4685]])

In [9]:
X.size()

torch.Size([2, 3])

# Tensor addition

In [10]:
X = torch.tensor([[2, 7, 9],[1, 4, 5]])
Y = torch.tensor([[20, 70, 90],[10, 40, 50]])

#method 1:
Z = X + Y
print(Z)

tensor([[22, 77, 99],
        [11, 44, 55]])


In [11]:
#method 2
torch.add(X, Y)

tensor([[22, 77, 99],
        [11, 44, 55]])

In [12]:
# method 3

#create an empty tensor
rslt = torch.empty_like(X)
whatever_you_put_in_here = torch.add(X, Y, out=rslt)
print(rslt)

tensor([[22, 77, 99],
        [11, 44, 55]])


In [13]:
# method 4

#addition in place: This operation adds the tensor at out with the tensor inside the brace and update the tensor at out
Y.add_(X)
Y

tensor([[22, 77, 99],
        [11, 44, 55]])

# Additional features:

1. To multiply 2 tensors: <b>torch.mm(X, Y)</b>
2. To convert from numpy to torch tensor: <b>torch.from_numpy(numpy_array)</b>


In [15]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    Y = torch.ones_like(X, device=device)  # directly create a tensor on GPU
    X = X.to(device)                       # or just use strings ``.to("cuda")``
    z = X + Y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 3,  8, 10],
        [ 2,  5,  6]], device='cuda:0')
tensor([[ 3.,  8., 10.],
        [ 2.,  5.,  6.]], dtype=torch.float64)
