<a href="https://colab.research.google.com/github/sadat1971/PyTorch_practice/blob/main/002_PyTorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd: Automatic Differentiation of Tensor

In [1]:
import torch 
import numpy as np

In [5]:
X = torch.tensor(4., requires_grad=True)  #define the variable with the value you want the differentiation in 
Y = X**2 # Define Y as a function of X
Y.backward() #Perform the differentiation
X.grad #What you will obtain after differentiation

tensor(8.)

In [6]:
X = torch.ones((4,4), requires_grad=True)
X

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

In [7]:
Y = 3*X + 4
Y

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]], grad_fn=<AddBackward0>)

In [10]:
print(X.grad_fn) # X wasnot created as a result of an operation, so it has no grad_fn
print(Y.grad_fn) # Y was created as a result of an operation, so it has a grad_fn

None


In [11]:
Y.mean()

tensor(7., grad_fn=<MeanBackward0>)

In [12]:
Y.requires_grad

True

In [15]:
# Now, not all the time we need the gradient. Sometimes, the backtracking can be expensive
Z = Y.detach()
Z

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])

In [22]:
# Another way is to use the with torch.no_grad()

with torch.no_grad():
  Y_prime = 3*X + 4 
  print(Y_prime)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]], grad_fn=<AddBackward0>)
tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
